import { useEffect, useState } from 'react'
import { Check, Download, FileText, Megaphone, RefreshCw, ShieldCheck, UserPlus, X } from 'lucide-react'
import { adminCalcularFechamento, adminFinanceiroWorkspace, adminJustifications, adminMedicalLeaves, adminPayslips, adminPoint, adminProntuario, adminQuitarParcela, adminRelatorioFechamento, adminRequests, adminRights, adminCadastrarFuncionario, answerRequest, decideJustification, decideMedicalLeave, listEmployees, publishNotice, registerPayslip, updateLot, updateOrder } from '../lib/api'
import type { AdminJustificationRow, AdminLotRow, AdminMedicalLeaveRow, AdminOrderRow, AdminPayslipRow, AdminPointRow, AdminRequestRow, EmployeeRow, FinanceiroWorkspace, ProntuarioResponse } from '../lib/types'
import { EmptyState, ErrorState, PageHeading, Pagination, SectionCard, StatusLegend, StatusPill, formatDate, formatMoney, statusContext } from '../components/ui'
import { FinanceWriteForms } from './FinanceWriteForms'

type Tab = 'ponto'|'justificativas'|'atestados'|'solicitacoes'|'cadastro'|'prontuario'|'fechamento'|'holerites'|'avisos'|'financeiro'|'producao'
const PAGE_SIZE = 8
const v = (x: unknown) => x === null || x === undefined || x === '' ? '—' : String(x)

function printRows(title: string, headers: string[], rows: string[][]) {
  const esc = (x: string) => x.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c))
  const html = `<html><head><title>${esc(title)}</title><style>body{font:12px Arial;padding:24px;color:#17202b}table{border-collapse:collapse;width:100%}td,th{border:1px solid #d2d9e2;padding:7px;text-align:left}th{background:#eef2f6}</style></head><body><h1>${esc(title)}</h1><p>RF Gestão · gerado em ${new Date().toLocaleString('pt-BR')}</p><table><thead><tr>${headers.map(esc).map(x => `<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(x => `<td>${esc(x || '—')}</td>`).join('')}</tr>`).join('')}</tbody></table><script>onload=()=>print()</script></body></html>`
  const windowRef = window.open('', '_blank')
  if (windowRef) { windowRef.document.write(html); windowRef.document.close() }
}

function PageSummary({ label, value, detail }: { label: string; value: string | number; detail: string }) {
  return <div className="admin-summary"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>
}

export function AdminCenterV2({ token, initialTab = 'ponto' }: { token: string; initialTab?: Tab }) {
  const [tab, setActiveTab] = useState<Tab>(initialTab)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [pages, setPages] = useState<Record<string, number>>({})
  const [point, setPoint] = useState<AdminPointRow[]>([])
  const [justs, setJusts] = useState<AdminJustificationRow[]>([])
  const [leaves, setLeaves] = useState<AdminMedicalLeaveRow[]>([])
  const [requests, setRequests] = useState<AdminRequestRow[]>([])
  const [slips, setSlips] = useState<AdminPayslipRow[]>([])
  const [employees, setEmployees] = useState<EmployeeRow[]>([])
  const [orders, setOrders] = useState<AdminOrderRow[]>([])
  const [lots, setLots] = useState<AdminLotRow[]>([])
  const [fin, setFin] = useState<FinanceiroWorkspace | null>(null)
  const [reply, setReply] = useState<Record<string, string>>({})
  const [selected, setSelected] = useState('')
  const [record, setRecord] = useState<ProntuarioResponse | null>(null)
  const [competencia, setCompetencia] = useState(new Date().toISOString().slice(0, 7))
  const [informais, setInformais] = useState(false)
  const [notice, setNotice] = useState({ titulo: '', conteudo: '', prioridade: 'normal' })
  const [slip, setSlip] = useState({ funcionarioId: '', mes: String(new Date().getMonth() + 1), ano: String(new Date().getFullYear()), nome: '', url: '' })
  const [emp, setEmp] = useState({ nome: '', cpf: '', dataNascimento: '', tipoVinculo: 'formal', cargo: '', telefone: '', endereco: '', valorMensal: '', valorDiaria: '', liberarAcesso: true })

  async function load() {
    setLoading(true); setError('')
    try {
      const [p, j, a, s, h, r, e, f] = await Promise.all([adminPoint(token), adminJustifications(token), adminMedicalLeaves(token), adminRequests(token), adminPayslips(token), adminRights(token), listEmployees(token), adminFinanceiroWorkspace(token)])
      if (!p.sucesso) throw new Error(p.erro || 'Acesso negado')
      setPoint(p.registros || []); setJusts(j.justificativas || []); setLeaves(a.atestados || []); setRequests(s.solicitacoes || [])
      setSlips(h.holerites || []); setOrders(r.ordens || []); setLots(r.producao || []); setEmployees(e || []); setFin(f)
    } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao carregar a central') } finally { setLoading(false) }
  }

  useEffect(() => { load() }, [token])

  async function act(fn: () => Promise<{ sucesso: boolean; erro?: string }>, ok: string) {
    setError(''); setMessage('')
    try { const result = await fn(); if (!result.sucesso) throw new Error(result.erro || 'Operação não concluída'); setMessage(ok); await load() }
    catch (err) { setError(err instanceof Error ? err.message : 'Operação não concluída') }
  }

  function setTabState(next: Tab) { setActiveTab(next); setMessage(''); setError(''); setPages(current => ({ ...current, [next]: 1 })) }
  function pageFor(key: string, total: number) { return Math.min(pages[key] || 1, Math.max(1, Math.ceil(total / PAGE_SIZE))) }
  function pageItems<T>(key: string, items: T[]) { const page = pageFor(key, items.length); return items.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE) }
  function pager(key: string, total: number) { return <Pagination page={pageFor(key, total)} total={total} pageSize={PAGE_SIZE} onChange={page => setPages(current => ({ ...current, [key]: page }))} /> }

  async function openRecord(id: string) {
    setSelected(id); setRecord(null); if (!id) return
    try { const result = await adminProntuario(token, id); if (!result.sucesso) throw new Error(result.erro || 'Prontuário não encontrado'); setRecord(result) }
    catch (err) { setError(err instanceof Error ? err.message : 'Falha ao abrir prontuário') }
  }

  async function report(type: 'escritorio' | 'vale') {
    try { const result = await adminRelatorioFechamento(token, competencia, type, informais); if (!result.sucesso) throw new Error(result.erro || 'Calcule o fechamento antes'); const first = (result.linhas || [])[0] || {}; printRows(`${type === 'vale' ? 'Vale-alimentação' : 'Escritório'} · ${competencia}`, Object.keys(first), (result.linhas || []).map(row => Object.values(row).map(value => String(value ?? '')))); setMessage('Relatório pronto para impressão ou PDF') }
    catch (err) { setError(err instanceof Error ? err.message : 'Falha ao gerar relatório') }
  }

  if (loading) return <><PageHeading eyebrow="Administração total" title="Central operacional" description="Carregando dados e permissões…" /><SectionCard title="Sincronizando ambiente" caption="Conectando às fontes reais do Supabase"><div className="state-card"><RefreshCw className="spin" size={20} /> Consultando dados operacionais.</div></SectionCard></>

  const tabs: [Tab, string][] = [['ponto', 'Ponto geral'], ['justificativas', 'Justificativas'], ['atestados', 'Atestados'], ['solicitacoes', 'Solicitações RH'], ['cadastro', 'Cadastro de vínculo'], ['prontuario', 'Prontuários'], ['fechamento', 'Fechamento mensal'], ['holerites', 'Holerites'], ['avisos', 'Avisos'], ['financeiro', 'Financeiro'], ['producao', 'Produção']]
  const financialItems = [...(fin?.contas || []), ...(fin?.dividas || []), ...(fin?.parcelas || [])]

  return <>
    <PageHeading eyebrow="Administração total · RF Gestão" title="Central operacional" description="Um cockpit para executar, revisar e acompanhar toda a operação." action={<button className="secondary-button" onClick={load}><RefreshCw size={16} /> Atualizar dados</button>} />
    <div className="admin-overview"><PageSummary label="Equipe ativa" value={employees.length} detail="cadastros disponíveis" /><PageSummary label="Ponto" value={point.length} detail="registros carregados" /><PageSummary label="Financeiro" value={financialItems.length} detail="compromissos monitorados" /><PageSummary label="Atenção" value={requests.length + justs.length + leaves.length} detail="itens aguardando análise" /></div><div className="dashboard-signal admin-signal"><div><strong>Centro de decisão</strong><span>Use a cor para priorizar. O texto explica o motivo e confirma a leitura.</span></div><StatusLegend /></div>
    <div className="admin-tabs" role="tablist">{tabs.map(([key, label]) => <button role="tab" aria-selected={tab === key} key={key} className={tab === key ? 'active' : ''} onClick={() => setTabState(key)}>{label}</button>)}</div>
    {message && <div className="form-success inline-message"><Check size={16} /> {message}</div>}
    {error && <ErrorState message={error} />}

    {tab === 'ponto' && <SectionCard title="Ponto geral" caption={`${point.length} registros · leitura operacional por página`}><div className="section-toolbar"><span className="toolbar-note">A jornada é exibida com funcionário, data, horários e status.</span><button className="secondary-button" onClick={() => printRows('Ponto geral', ['Data', 'Funcionário', 'CPF', 'Entrada', 'Saída', 'Horas', 'Status'], point.map(row => [formatDate(row.data), row.nome, row.cpf, row.entrada || '', row.saida || '', row.horas_trabalhadas || '', row.status || '']))}><Download size={16} /> Exportar tudo</button></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Funcionário</th><th>CPF</th><th>Entrada</th><th>Saída</th><th>Horas</th><th>Status</th></tr></thead><tbody>{pageItems('ponto', point).map(row => <tr key={row.id}><td>{formatDate(row.data)}</td><td><strong>{row.nome}</strong><small>{row.cargo || ''}</small></td><td className="mono">{row.cpf}</td><td>{row.entrada || '—'}</td><td>{row.saida || '—'}</td><td>{row.horas_trabalhadas || '—'}</td><td><StatusPill value={row.status} detail={statusContext(row.status)} /></td></tr>)}</tbody></table></div>{pager('ponto', point.length)}</SectionCard>}

    {tab === 'justificativas' && <SectionCard title="Justificativas de ponto" caption={`${justs.length} solicitações · decisão e resposta ficam registradas`}><div className="document-list">{pageItems('justificativas', justs).map(row => <div className="document-row" key={row.id}><div><strong>{row.nome} · {row.tipo}</strong><small>{formatDate(row.data_registro)} · {row.motivo}</small><input className="inline-input" placeholder="Resposta do RH" value={reply[row.id] || ''} onChange={event => setReply({ ...reply, [row.id]: event.target.value })} /></div><StatusPill value={row.status} /><button className="icon-button" aria-label="Aceitar justificativa" onClick={() => act(() => decideJustification(token, row.id, 'aceita', reply[row.id] || ''), 'Justificativa aceita.')}><Check size={16} /></button><button className="icon-button danger" aria-label="Recusar justificativa" onClick={() => act(() => decideJustification(token, row.id, 'recusada', reply[row.id] || ''), 'Justificativa recusada.')}><X size={16} /></button></div>)}</div>{justs.length ? pager('justificativas', justs.length) : <EmptyState title="Nenhuma justificativa" description="Novos pedidos aparecerão aqui." />}</SectionCard>}

    {tab === 'atestados' && <SectionCard title="Validação de atestados" caption={`${leaves.length} documentos · revisão do RH`}><div className="document-list">{pageItems('atestados', leaves).map(row => <div className="document-row" key={row.id}><div><strong>{row.nome} · {row.tipo}</strong><small>{formatDate(row.data_atendimento)} · {row.dias} dia(s) · {row.arquivo_nome || 'sem arquivo'}</small><input className="inline-input" placeholder="Observação do RH" value={reply[row.id] || ''} onChange={event => setReply({ ...reply, [row.id]: event.target.value })} /></div><StatusPill value={row.status_label || row.status} /><button className="icon-button" aria-label="Aceitar atestado" onClick={() => act(() => decideMedicalLeave(token, row.id, 'aceito', reply[row.id] || ''), 'Atestado aceito.')}><Check size={16} /></button><button className="icon-button danger" aria-label="Recusar atestado" onClick={() => act(() => decideMedicalLeave(token, row.id, 'recusado', reply[row.id] || ''), 'Atestado recusado.')}><X size={16} /></button></div>)}</div>{leaves.length ? pager('atestados', leaves.length) : <EmptyState title="Nenhum atestado pendente" description="Os atestados enviados aparecerão aqui." />}</SectionCard>}

    {tab === 'solicitacoes' && <SectionCard title="Solicitações ao RH" caption={`${requests.length} solicitações · acompanhamento por status`}><div className="document-list">{pageItems('solicitacoes', requests).map(row => <div className="document-row" key={row.id}><div><strong>{row.nome} · {row.tipo}</strong><small>{formatDate(row.created_at)} · {row.descricao}</small><textarea className="inline-input" rows={2} placeholder="Resposta ao funcionário" value={reply[row.id] || ''} onChange={event => setReply({ ...reply, [row.id]: event.target.value })} /></div><select value={row.status} onChange={event => act(() => answerRequest(token, row.id, event.target.value, reply[row.id] || ''), 'Solicitação atualizada.')}><option value="em_analise">Em análise</option><option value="atendida">Atendida</option><option value="recusada">Recusada</option></select></div>)}</div>{requests.length ? pager('solicitacoes', requests.length) : <EmptyState title="Nenhuma solicitação" description="Os pedidos dos funcionários aparecerão aqui." />}</SectionCard>}

    {tab === 'cadastro' && <SectionCard title="Cadastrar funcionário" caption="Crie o vínculo e, se necessário, libere o primeiro acesso ao portal"><form className="form-stack" onSubmit={event => { event.preventDefault(); act(() => adminCadastrarFuncionario(token, { nome: emp.nome, cpf: emp.cpf, dataNascimento: emp.dataNascimento, tipoVinculo: emp.tipoVinculo, cargo: emp.cargo, telefone: emp.telefone, endereco: emp.endereco, valorMensal: emp.valorMensal ? Number(emp.valorMensal) : null, valorDiaria: emp.valorDiaria ? Number(emp.valorDiaria) : null, liberarAcesso: emp.liberarAcesso }), 'Funcionário cadastrado.') }}><div className="form-row"><label>Nome completo<input required value={emp.nome} onChange={event => setEmp({ ...emp, nome: event.target.value })} /></label><label>CPF<input required inputMode="numeric" value={emp.cpf} onChange={event => setEmp({ ...emp, cpf: event.target.value })} /></label></div><div className="form-row"><label>Data de nascimento<input required type="date" value={emp.dataNascimento} onChange={event => setEmp({ ...emp, dataNascimento: event.target.value })} /></label><label>Tipo de vínculo<select value={emp.tipoVinculo} onChange={event => setEmp({ ...emp, tipoVinculo: event.target.value })}><option value="formal">Formal / CLT</option><option value="informal">Informal</option><option value="experiencia">Experiência · 3 meses</option></select></label></div><div className="form-row"><label>Cargo<input value={emp.cargo} onChange={event => setEmp({ ...emp, cargo: event.target.value })} /></label><label>Telefone<input value={emp.telefone} onChange={event => setEmp({ ...emp, telefone: event.target.value })} /></label></div><label>Endereço<input value={emp.endereco} onChange={event => setEmp({ ...emp, endereco: event.target.value })} /></label><div className="form-row"><label>Valor mensal<input type="number" step="0.01" value={emp.valorMensal} onChange={event => setEmp({ ...emp, valorMensal: event.target.value })} /></label><label>Valor da diária<input type="number" step="0.01" value={emp.valorDiaria} onChange={event => setEmp({ ...emp, valorDiaria: event.target.value })} /></label></div><label className="check-line"><input type="checkbox" checked={emp.liberarAcesso} onChange={event => setEmp({ ...emp, liberarAcesso: event.target.checked })} /> Liberar portal com senha inicial DDMMAAAA</label><button className="primary-button" type="submit"><UserPlus size={16} /> Criar vínculo</button></form></SectionCard>}

    {tab === 'prontuario' && <div className="two-column"><SectionCard title="Prontuário por funcionário" caption="Cadastro, documentos, RH, ponto e timeline"><select value={selected} onChange={event => openRecord(event.target.value)}><option value="">Selecione um funcionário</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.nome} · {employee.cpf}</option>)}</select>{record?.funcionario ? <div className="profile-summary"><strong>{v(record.funcionario.nome)}</strong><small>{v(record.funcionario.cpf)} · {v(record.funcionario.tipo_vinculo)} · {record.funcionario.registrado ? 'elegível para escritório' : 'fora da folha oficial'}</small><div className="metric-grid compact"><div><b>{record.ponto.length}</b><small>pontos</small></div><div><b>{record.atestados.length}</b><small>atestados</small></div><div><b>{record.justificativas.length}</b><small>justificativas</small></div></div></div> : <EmptyState title="Selecione um cadastro" description="A visão individual evita misturar dados de pessoas diferentes." />}</SectionCard>{record && <SectionCard title="Linha do tempo" caption="Eventos recentes do vínculo"><div className="document-list">{pageItems('timeline', record.timeline).map((row, index) => <div className="document-row" key={String(row.id || index)}><div><strong>{v(row.evento)}</strong><small>{v(row.data_evento)} · {v(row.descricao)}</small></div></div>)}</div>{pager('timeline', record.timeline.length)}<div className="callout"><FileText size={18} /><p>{record.documentos.length} documentos e {record.advertencias.length} advertências neste prontuário.</p></div></SectionCard>}</div>}

    {tab === 'fechamento' && <div className="two-column"><SectionCard title="Fechamento mensal" caption="Calcule horas extras, faltas, DSR e regras do benefício"><label>Competência<input type="month" value={competencia} onChange={event => setCompetencia(event.target.value)} /></label><label className="check-line"><input type="checkbox" checked={informais} onChange={event => setInformais(event.target.checked)} /> Incluir informais no relatório do vale</label><button className="primary-button" onClick={() => act(() => adminCalcularFechamento(token, competencia, informais), `Fechamento ${competencia} calculado.`)}>Calcular fechamento</button><div className="callout"><ShieldCheck size={18} /><p>O escritório recebe somente vínculos formais. O vale pode incluir informais e exclui faltas injustificadas.</p></div></SectionCard><SectionCard title="Emitir relatórios" caption="A impressão abre em uma nova janela para salvar como PDF"><button className="secondary-button" onClick={() => report('escritorio')}><Download size={16} /> Relatório do escritório</button><button className="secondary-button" onClick={() => report('vale')}><Download size={16} /> Relatório do vale-alimentação</button></SectionCard></div>}

    {tab === 'holerites' && <div className="two-column"><SectionCard title="Publicar holerite" caption="Disponível somente para vínculos formais"><form className="form-stack" onSubmit={event => { event.preventDefault(); act(() => registerPayslip(token, slip.funcionarioId, Number(slip.mes), Number(slip.ano), slip.nome, slip.url), 'Holerite publicado.') }}><label>Funcionário<select required value={slip.funcionarioId} onChange={event => setSlip({ ...slip, funcionarioId: event.target.value })}><option value="">Selecione</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.nome} · {employee.cpf}</option>)}</select></label><div className="form-row"><label>Mês<input type="number" min="1" max="12" value={slip.mes} onChange={event => setSlip({ ...slip, mes: event.target.value })} /></label><label>Ano<input type="number" value={slip.ano} onChange={event => setSlip({ ...slip, ano: event.target.value })} /></label></div><label>Nome do arquivo<input required value={slip.nome} onChange={event => setSlip({ ...slip, nome: event.target.value })} /></label><label>URL do arquivo<input required type="url" value={slip.url} onChange={event => setSlip({ ...slip, url: event.target.value })} /></label><button className="primary-button" type="submit">Publicar para o funcionário</button></form></SectionCard><SectionCard title="Holerites publicados" caption={`${slips.length} registros disponíveis`}><div className="document-list">{pageItems('holerites', slips).map(row => <div className="document-row" key={row.id}><div><strong>{row.nome} · {String(row.mes).padStart(2, '0')}/{row.ano}</strong><small>{row.arquivo_nome || 'Arquivo'}</small></div><a className="icon-button" href={row.arquivo_url} target="_blank" rel="noreferrer" aria-label="Baixar holerite"><Download size={16} /></a></div>)}</div>{slips.length ? pager('holerites', slips.length) : <EmptyState title="Nenhum holerite publicado" description="Publique o primeiro comprovante para disponibilizá-lo no portal." />}</SectionCard></div>}

    {tab === 'avisos' && <SectionCard title="Publicar aviso" caption="Comunicados ficam visíveis para toda a empresa"><form className="form-stack" onSubmit={event => { event.preventDefault(); act(() => publishNotice(token, notice.titulo, notice.conteudo, notice.prioridade), 'Aviso publicado para todos os funcionários.'); setNotice({ titulo: '', conteudo: '', prioridade: 'normal' }) }}><div className="form-row"><label>Título<input required value={notice.titulo} onChange={event => setNotice({ ...notice, titulo: event.target.value })} /></label><label>Prioridade<select value={notice.prioridade} onChange={event => setNotice({ ...notice, prioridade: event.target.value })}><option value="normal">Normal</option><option value="importante">Importante</option><option value="urgente">Urgente</option></select></label></div><label>Comunicado<textarea required rows={7} value={notice.conteudo} onChange={event => setNotice({ ...notice, conteudo: event.target.value })} /></label><button className="primary-button" type="submit"><Megaphone size={16} /> Publicar comunicado</button></form></SectionCard>}

    {tab === 'financeiro' && <><div className="two-column"><SectionCard title="Contas, dívidas e parcelas" caption={`${financialItems.length} compromissos · dados reais e fonte preservada`}><div className="document-list">{pageItems('financeiro', financialItems).map((item, index) => <div className="document-row" key={String(item.id || index)}><div><strong>{v(item.descricao || item.categoria || 'Dívida / parcela')} · {formatMoney(Number(item.saldo_devedor || item.valor || 0))}</strong><small>{v(item.vencimento)} · {v(item.status)}{item.credor ? ` · ${v(item.credor)}` : ''}{item.fonte_documento ? ` · Fonte: ${v(item.fonte_documento)}` : ''}</small></div><StatusPill value={v(item.status)} detail={statusContext(v(item.status))} />{Boolean(item.numero) && item.status !== 'pago' && <button className="icon-button" aria-label="Baixar parcela" onClick={() => act(() => adminQuitarParcela(token, String(item.id)), 'Parcela baixada.')}><Check size={16} /></button>}</div>)}</div>{financialItems.length ? pager('financeiro', financialItems.length) : <EmptyState title="Nenhum compromisso novo" description="Contas, dívidas e parcelamentos aparecerão aqui." />}</SectionCard><SectionCard title="Recorrências" caption={`${fin?.recorrencias?.length || 0} custos recorrentes`}><div className="document-list">{pageItems('recorrencias', fin?.recorrencias || []).map((item, index) => <div className="document-row" key={String(item.id || index)}><div><strong>{v(item.descricao)}</strong><small>{v(item.periodicidade)} · {formatMoney(Number(item.valor || 0))} · próximo {v(item.proximo_vencimento)}</small></div><StatusPill value={item.ativo ? 'Ativa' : 'Inativa'} /></div>)}</div>{(fin?.recorrencias?.length || 0) ? pager('recorrencias', fin?.recorrencias?.length || 0) : <EmptyState title="Nenhuma recorrência" description="Cadastre custos que devem ser acompanhados mês a mês." />}<div className="callout"><ShieldCheck size={18} /><p>Comprovantes ficam vinculados à parcela baixada, preservando trilha de auditoria.</p></div></SectionCard></div><FinanceWriteForms token={token} onDone={load} /></>}

    {tab === 'producao' && <div className="two-column"><SectionCard title="Ordens de serviço" caption={`${orders.length} ordens · andamento da produção`}><div className="document-list">{pageItems('ordens', orders).map(row => <div className="document-row" key={row.id}><div><strong>{row.numero} · {row.descricao}</strong><small>{row.quantidade} unidades · {formatMoney(row.valor_total)}</small></div><StatusPill value={row.status} detail={statusContext(row.status)} /><select value={row.status} onChange={event => act(() => updateOrder(token, row.id, event.target.value), 'Ordem atualizada.')}><option value="recebida">Recebida</option><option value="em_producao">Em produção</option><option value="costurada">Costurada</option><option value="expedida">Expedida</option><option value="entregue">Entregue</option></select></div>)}</div>{orders.length ? pager('ordens', orders.length) : <EmptyState title="Nenhuma ordem cadastrada" description="As ordens criadas pelo administrador aparecerão aqui." />}</SectionCard><SectionCard title="Lotes de produção" caption={`${lots.length} lotes · acompanhamento operacional`}><div className="document-list">{pageItems('lotes', lots).map(row => <div className="document-row" key={row.id}><div><strong>{row.nome}</strong><small>{row.quantidade} unidades · {row.responsavel || 'sem responsável'}</small></div><StatusPill value={row.status} detail={statusContext(row.status)} /><select value={row.status} onChange={event => act(() => updateLot(token, row.id, event.target.value), 'Lote atualizado.')}><option value="em_costura">Em costura</option><option value="costurado">Costurado</option><option value="entregue">Entregue</option><option value="pago">Pago</option></select></div>)}</div>{lots.length ? pager('lotes', lots.length) : <EmptyState title="Nenhum lote cadastrado" description="Os lotes em produção aparecerão aqui." />}</SectionCard></div>}
  </>
}
