import { useEffect, useState } from 'react'
import { Check, Download, Megaphone, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { adminJustifications, adminMedicalLeaves, adminPayslips, adminPoint, adminRequests, adminRights, answerRequest, decideJustification, decideMedicalLeave, listEmployees, publishNotice, registerPayslip, updateDebt, updateLot, updateOrder } from '../lib/api'
import type { AdminDebtRow, AdminJustificationRow, AdminLotRow, AdminMedicalLeaveRow, AdminOrderRow, AdminPayslipRow, AdminPointRow, AdminRequestRow, EmployeeRow } from '../lib/types'
import { EmptyState, ErrorState, PageHeading, SectionCard, StatusPill, formatDate, formatMoney } from '../components/ui'

type Tab = 'ponto' | 'justificativas' | 'atestados' | 'solicitacoes' | 'holerites' | 'avisos' | 'financeiro' | 'producao'

function printRows(title: string, headers: string[], rows: string[][]) {
  const esc = (v: string) => v.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c))
  const html = `<html><head><title>${esc(title)}</title><style>body{font:12px Arial;padding:24px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #bbb;padding:6px;text-align:left}th{background:#eee}</style></head><body><h1>${esc(title)}</h1><table><thead><tr>${headers.map((h) => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((v) => `<td>${esc(v || '—')}</td>`).join('')}</tr>`).join('')}</tbody></table><script>onload=()=>print()</script></body></html>`
  const w = window.open('', '_blank'); if (w) { w.document.write(html); w.document.close() }
}

export function AdminCenter({ token }: { token: string }) {
  const [tab, setTab] = useState<Tab>('ponto')
  const [point, setPoint] = useState<AdminPointRow[]>([]); const [justifications, setJustifications] = useState<AdminJustificationRow[]>([]); const [leaves, setLeaves] = useState<AdminMedicalLeaveRow[]>([]); const [requests, setRequests] = useState<AdminRequestRow[]>([]); const [payslips, setPayslips] = useState<AdminPayslipRow[]>([]); const [employees, setEmployees] = useState<EmployeeRow[]>([]); const [debts, setDebts] = useState<AdminDebtRow[]>([]); const [orders, setOrders] = useState<AdminOrderRow[]>([]); const [lots, setLots] = useState<AdminLotRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [notice, setNotice] = useState({ titulo: '', conteudo: '', prioridade: 'normal' }); const [reply, setReply] = useState<Record<string, string>>({})
  const [slip, setSlip] = useState({ funcionarioId: '', mes: String(new Date().getMonth() + 1), ano: String(new Date().getFullYear()), nome: '', url: '' })
  async function load() { setLoading(true); setError(''); try { const [p,j,a,s,h,r,e] = await Promise.all([adminPoint(token), adminJustifications(token), adminMedicalLeaves(token), adminRequests(token), adminPayslips(token), adminRights(token), listEmployees(token)]); if (!p.sucesso) throw new Error(p.erro || 'Acesso negado'); setPoint(p.registros || []); setJustifications(j.justificativas || []); setLeaves(a.atestados || []); setRequests(s.solicitacoes || []); setPayslips(h.holerites || []); setDebts(r.dividas || []); setOrders(r.ordens || []); setLots(r.producao || []); setEmployees(e || []) } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao carregar a central administrativa.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [token])
  async function act(fn: () => Promise<{ sucesso: boolean; erro?: string }>, ok: string) { try { const result = await fn(); if (!result.sucesso) throw new Error(result.erro || 'Operação não concluída'); setMessage(ok); await load() } catch (err) { setError(err instanceof Error ? err.message : 'Operação não concluída') } }
  const tabs: [Tab, string][] = [['ponto', 'Ponto geral'], ['justificativas', 'Justificativas'], ['atestados', 'Atestados'], ['solicitacoes', 'Solicitações RH'], ['holerites', 'Holerites'], ['avisos', 'Publicar avisos'], ['financeiro', 'Dívidas'], ['producao', 'Produção']]
  if (loading) return <><PageHeading eyebrow="Administração total" title="Central operacional" description="Carregando permissões e dados da empresa…" /><SectionCard title="Sincronizando" caption="Renan Ricardo · acesso total"><div className="state-card"><RefreshCw className="spin" size={20} /> Consultando RH, ponto, financeiro e produção.</div></SectionCard></>
  return <><PageHeading eyebrow="Administração total · Renan Ricardo" title="Central operacional" description="Acesso completo ao ambiente: ponto, RH, holerites, comunicação, financeiro, produção e funcionários." action={<button className="secondary-button" onClick={load}><RefreshCw size={16} /> Atualizar</button>} /><div className="admin-tabs">{tabs.map(([key, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => { setTab(key); setMessage(''); setError('') }}>{label}</button>)}</div>{message && <div className="form-success inline-message"><Check size={16} />{message}</div>}{error && <ErrorState message={error} />}
  {tab === 'ponto' && <SectionCard title={`${point.length} registros de ponto`} caption="Todos os funcionários ativos"><button className="secondary-button" onClick={() => printRows('Ponto geral', ['Data','Funcionário','CPF','Entrada','Saída','Horas','Status'], point.map((r) => [formatDate(r.data), r.nome, r.cpf, r.entrada || '', r.saida || '', r.horas_trabalhadas || '', r.status || '']))}><Download size={16} /> Exportar ponto</button><div className="table-wrap"><table><thead><tr><th>Data</th><th>Funcionário</th><th>CPF</th><th>Entrada</th><th>Saída</th><th>Horas</th><th>Status</th></tr></thead><tbody>{point.map((r) => <tr key={r.id}><td>{formatDate(r.data)}</td><td><strong>{r.nome}</strong><small>{r.cargo || ''}</small></td><td className="mono">{r.cpf}</td><td>{r.entrada || '—'}</td><td>{r.saida || '—'}</td><td>{r.horas_trabalhadas || '—'}</td><td><StatusPill value={r.status} /></td></tr>)}</tbody></table></div></SectionCard>}
  {tab === 'justificativas' && <SectionCard title="Justificativas de ponto" caption="Aceite ou recuse com resposta ao funcionário">{justifications.length === 0 ? <EmptyState title="Nenhuma justificativa" description="Novos pedidos aparecerão aqui." /> : <div className="document-list">{justifications.map((r) => <div className="document-row" key={r.id}><div><strong>{r.nome} · {r.tipo}</strong><small>{formatDate(r.data_registro)} · {r.motivo}</small><input className="inline-input" placeholder="Resposta do RH" value={reply[r.id] || ''} onChange={(e) => setReply({ ...reply, [r.id]: e.target.value })} /></div><StatusPill value={r.status} /><button className="icon-button" onClick={() => act(() => decideJustification(token, r.id, 'aceita', reply[r.id] || ''), 'Justificativa aceita.')}><Check size={16} /></button><button className="icon-button danger" onClick={() => act(() => decideJustification(token, r.id, 'recusada', reply[r.id] || ''), 'Justificativa recusada.')}><X size={16} /></button></div>)}</div>}</SectionCard>}
  {tab === 'atestados' && <SectionCard title="Validação de atestados" caption="O RH decide e registra a observação">{leaves.length === 0 ? <EmptyState title="Nenhum atestado pendente" description="Os atestados enviados pelos funcionários aparecerão aqui." /> : <div className="document-list">{leaves.map((r) => <div className="document-row" key={r.id}><div><strong>{r.nome} · {r.tipo}</strong><small>{formatDate(r.data_atendimento)} · {r.dias} dia(s) · {r.arquivo_nome || 'sem arquivo'}</small><input className="inline-input" placeholder="Observação do RH" value={reply[r.id] || ''} onChange={(e) => setReply({ ...reply, [r.id]: e.target.value })} /></div><StatusPill value={r.status_label || r.status} /><button className="icon-button" onClick={() => act(() => decideMedicalLeave(token, r.id, 'aceito', reply[r.id] || ''), 'Atestado aceito.')}><Check size={16} /></button><button className="icon-button danger" onClick={() => act(() => decideMedicalLeave(token, r.id, 'recusado', reply[r.id] || ''), 'Atestado recusado.')}><X size={16} /></button></div>)}</div>}</SectionCard>}
  {tab === 'solicitacoes' && <SectionCard title="Solicitações ao RH" caption="Responda e altere o status de cada pedido">{requests.length === 0 ? <EmptyState title="Nenhuma solicitação" description="Os pedidos dos funcionários aparecerão aqui." /> : <div className="document-list">{requests.map((r) => <div className="document-row" key={r.id}><div><strong>{r.nome} · {r.tipo}</strong><small>{formatDate(r.created_at)} · {r.descricao}</small><textarea className="inline-input" rows={2} placeholder="Resposta ao funcionário" value={reply[r.id] || ''} onChange={(e) => setReply({ ...reply, [r.id]: e.target.value })} /></div><select value={r.status} onChange={(e) => act(() => answerRequest(token, r.id, e.target.value, reply[r.id] || ''), 'Solicitação atualizada.')}><option value="em_analise">Em análise</option><option value="atendida">Atendida</option><option value="recusada">Recusada</option></select></div>)}</div>}</SectionCard>}
  {tab === 'holerites' && <div className="two-column"><SectionCard title="Publicar holerite" caption="Informe uma URL privada ou do Storage"><form className="form-stack" onSubmit={(e) => { e.preventDefault(); act(() => registerPayslip(token, slip.funcionarioId, Number(slip.mes), Number(slip.ano), slip.nome, slip.url), 'Holerite publicado.') }}><label>Funcionário<select required value={slip.funcionarioId} onChange={(e) => setSlip({ ...slip, funcionarioId: e.target.value })}><option value="">Selecione</option>{employees.map((e) => <option key={e.id} value={e.id}>{e.nome} · {e.cpf}</option>)}</select></label><div className="form-row"><label>Mês<input type="number" min="1" max="12" value={slip.mes} onChange={(e) => setSlip({ ...slip, mes: e.target.value })} /></label><label>Ano<input type="number" value={slip.ano} onChange={(e) => setSlip({ ...slip, ano: e.target.value })} /></label></div><label>Nome do arquivo<input required value={slip.nome} onChange={(e) => setSlip({ ...slip, nome: e.target.value })} /></label><label>URL do arquivo<input required type="url" value={slip.url} onChange={(e) => setSlip({ ...slip, url: e.target.value })} /></label><button className="primary-button" type="submit">Publicar para o funcionário</button></form></SectionCard><SectionCard title="Holerites publicados" caption={`${payslips.length} registros`}><div className="document-list">{payslips.map((r) => <div className="document-row" key={r.id}><div><strong>{r.nome} · {String(r.mes).padStart(2, '0')}/{r.ano}</strong><small>{r.arquivo_nome || 'Arquivo'}</small></div><a className="icon-button" href={r.arquivo_url} target="_blank" rel="noreferrer"><Download size={16} /></a></div>)}</div></SectionCard></div>}
  {tab === 'avisos' && <SectionCard title="Publicar aviso para a empresa" caption="O aviso ficará visível no portal dos funcionários"><form className="form-stack" onSubmit={(e) => { e.preventDefault(); act(() => publishNotice(token, notice.titulo, notice.conteudo, notice.prioridade), 'Aviso publicado para todos os funcionários.'); setNotice({ titulo: '', conteudo: '', prioridade: 'normal' }) }}><label>Título<input required value={notice.titulo} onChange={(e) => setNotice({ ...notice, titulo: e.target.value })} /></label><label>Prioridade<select value={notice.prioridade} onChange={(e) => setNotice({ ...notice, prioridade: e.target.value })}><option value="normal">Normal</option><option value="importante">Importante</option><option value="urgente">Urgente</option></select></label><label>Comunicado<textarea required rows={7} value={notice.conteudo} onChange={(e) => setNotice({ ...notice, conteudo: e.target.value })} /></label><button className="primary-button" type="submit"><Megaphone size={16} /> Publicar aviso</button></form></SectionCard>}
  {tab === 'financeiro' && <SectionCard title="Dívidas e baixas" caption="Atualize saldo e situação diretamente no financeiro"><div className="table-wrap"><table><thead><tr><th>Descrição</th><th>Credor</th><th>Saldo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{debts.map((r) => <tr key={r.id}><td>{r.descricao}</td><td>{r.credor}</td><td>{formatMoney(r.saldo_devedor)}</td><td><StatusPill value={r.status} /></td><td><select value={r.status} onChange={(e) => act(() => updateDebt(token, r.id, e.target.value, e.target.value === 'quitada' ? 0 : r.saldo_devedor), 'Dívida atualizada.')}><option value="ativa">Ativa</option><option value="renegociada">Renegociada</option><option value="quitada">Quitada</option></select></td></tr>)}</tbody></table></div></SectionCard>}
  {tab === 'producao' && <div className="two-column"><SectionCard title="Ordens de serviço" caption="Atualize o andamento da produção"><div className="document-list">{orders.map((r) => <div className="document-row" key={r.id}><div><strong>{r.numero} · {r.descricao}</strong><small>{r.quantidade} unidades · {formatMoney(r.valor_total)}</small></div><select value={r.status} onChange={(e) => act(() => updateOrder(token, r.id, e.target.value), 'Ordem atualizada.')}><option value="recebida">Recebida</option><option value="em_producao">Em produção</option><option value="costurada">Costurada</option><option value="expedida">Expedida</option><option value="entregue">Entregue</option><option value="cancelada">Cancelada</option></select></div>)}</div></SectionCard><SectionCard title="Lotes de produção" caption="Acompanhamento operacional"><div className="document-list">{lots.map((r) => <div className="document-row" key={r.id}><div><strong>{r.nome}</strong><small>{r.quantidade} unidades · {r.responsavel || 'sem responsável'}</small></div><select value={r.status} onChange={(e) => act(() => updateLot(token, r.id, e.target.value), 'Lote atualizado.')}><option value="em_costura">Em costura</option><option value="costurado">Costurado</option><option value="entregue">Entregue</option><option value="pago">Pago</option><option value="atrasado">Atrasado</option></select></div>)}</div></SectionCard></div>}
  <div className="callout"><ShieldCheck size={18} /><p>Este painel valida o perfil no servidor. Ocultar uma opção na interface não é a única proteção: cada consulta e alteração é autorizada por RPC no Supabase.</p></div></>
}
